################### Hibernate Configuration ##########################
server:
  port: 9003

################### Spring Configuration #############################
spring:
  application:
    name: microservice-notemanager
  data:
    mongodb:
      host: localhost
      port: 27017
      database : note

################### Log Configuration ################################
logging:
  level:
    org.springframework: INFO

microservice-patientmanager: microservice-patientmanager:9001