################### Hibernate Configuration ##########################
server:
  port: 9000

################### Spring Configuration ##############################
spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      routes:
      - id: microservice-clientui
        uri: http://localhost:9002
        predicates:
          - Path=/patient/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diabetedetect
    username: root
  jpa:
    show-sql: true

################### Log Configuration ################################
logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"