################### Hibernate Configuration ##########################
server:
  port: 9002

################### Spring Configuration #############################
spring:
  application:
    name: microservice-clientui

################### Log Configuration ################################
logging:
  level:
    org.springframework: INFO

microservice-gateway: microservice-gateway:9000
microservice-patientmanager: microservice-patientmanager:9001
microservice-notemanager: microservice-notemanager:9003
microservice-diabetesassessment: microservice-diabetesassessment:9004