################### Hibernate Configuration ##########################
server:
  port: 9002

################### Spring Configuration #############################
spring:
  application:
    name: MICROSERVICE-CLIENTUI

################### Log Configuration ################################
logging:
  level:
    org.springframework: INFO