################### Hibernate Configuration ##########################
server:
  port: 9004

################### Spring Configuration #############################
spring:
  application:
    name: microservice-diabetesassessment

################### Log Configuration ################################
logging:
  level:
    org.springframework: INFO

################### Ports Configuration ################################

microservice-patientmanager: microservice-patientmanager:9001
microservice-notemanager: microservice-notemanager:9003
